# ime workflowaa
name: Deploy workflow
# Sproži se ko se Test workflow zaključi
on:
  workflow_run:
    workflows: ["Test workflow"]
    types:
      - completed
jobs:
  deploy:
    # Zažene se samo če je Test workflow uspešno zaključen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      # Prenese kodo iz repozitorija
      - name: Checkout code
        uses: actions/checkout@v4
      # Prenese artefakt napaka.txt iz test workflowa
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: napaka
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}      
        # Preveri da je napaka.txt prazna, sicer ustavi
      - name: Check napaka.txt
        shell: powershell
        run: |
          if ((Get-Content napaka.txt).Length -gt 0) {
            Write-Output "Napaka.txt ni prazna - deploy se ustavi"
            exit 1
          }
      # Prijava na DockerHub
      - name: Login to DockerHub
        run: echo "dckr_pat_Rmc8qis_bHLhX9UYFXXJBe5Eq24" | docker login -u "anja21docker" --password-stdin
      # Zgradi Docker image
      - name: Build Docker image
        run: docker build -t anja21docker/preprosta_predobdelava_slik:latest .
      # Potisne Docker image na DockerHub
      - name: Push Docker image
        run: docker push anja21docker/preprosta_predobdelava_slik:latest
